server:
  port: 2201
  servlet:
    context-path: /chat

#mysql数据库配置 ?serverTimezone=GMT%2B8
spring:
  profiles:
    active: '@profileActive@'
  #    2.7兼容swagger3.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #时间戳统一转换 由于MvcConfig实现WebMvcConfigurer并有EnableWebMvc注解此配置不生效
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
#    2.6之后因循环引用导致启动报错
    allow-circular-references: true

## mybatis-plus 打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

